import { object, string, number, boolean, z } from "zod";

export const schemaRealEstate = object({
  nom: string(),
  surface: number(),
  addresse: string(),
  code_postal: number(),
  nbrbatiment: number(),
  nbrescalier: number(),
  nbrchambre: number(),
  numeroporte: number(),
  nbr_salle_bain: number(),
  ville_id: number(),
  typeBien_id: number(),
  proprietaire_id: number(),
  zoneStationnement: string(),
  anneeconstruction: string(),
  typemouvement: string(),
  ungarage: boolean().default(false),
  unecave: boolean().default(false),
  internet: boolean().default(false),
  dep_tvecranplat: boolean().default(false),
  exist_proxi_restaurant: boolean().default(false),
  pc_vide_ordure: boolean().default(false),
  pc_espace_vert: boolean().default(false),
  pc_eau_chaude_collective: boolean().default(false),
  pc_chauffage_collective: boolean().default(false),
  pc_interphone: boolean().default(false),
  exist_sous_sol: boolean().default(false),
  dep_lingemaison: boolean().default(false),
  exist_proxi_education: boolean().default(false),
  exist_salle_manger: boolean().default(false),
  exist_cheminee: boolean().default(false),
  pc_gardiennage: boolean().default(false),
  pc_antennetv_collective: boolean().default(false),
  exist_balcon: boolean().default(false),
  exist_proxi_centre_sante: boolean().default(false),
  pc_ascenseur: boolean().default(false),
  dep_lavevaiselle: boolean().default(false),
});

export type RealEstateType = z.infer<typeof schemaRealEstate>;
